void PythiaFullRunRoot(){
  gSystem->Load("libEG");
  gSystem->Load("libEGPythia6");
  //gSystem->Load("$HOME/alice/sw/ubuntu1804_x86-64/AliRoot/v5-09-47c-1/lib/libpythia6_4_28");
  gSystem->Load("libPythia6");
  //gSystem->Load("libAliPythia6");
  int EVN=100000;
  int HIGHEVN=10000;
  int ID=10;
  char* event1= Form("makeEventSample(%i,%i,350,7.7)",EVN,ID);
  char* event2= Form("makeEventSample(%i,%i,350,11.6)",EVN,ID);
  char* event3= Form("makeEventSample(%i,%i,350,19.5)",EVN,ID);
  char* event4= Form("makeEventSample(%i,%i,350,27)",EVN,ID);
  char* event5= Form("makeEventSample(%i,%i,350,39)",EVN,ID);
  char* event6= Form("makeEventSample(%i,%i,350,62.4)",EVN,ID);
  char* event7= Form("makeEventSample(%i,%i,350,130)",EVN,ID);
  char* event8= Form("makeEventSample(%i,%i,350,200)",EVN,ID);
  char* event9= Form("makeEventSample(%i,%i,350,900)",EVN,ID);
  char* event10= Form("makeEventSample(%i,%i,350,2760)",HIGHEVN,ID);
  char* event11= Form("makeEventSample(%i,%i,350,5020)",HIGHEVN,ID);
  char* event12= Form("makeEventSample(%i,%i,350,7000)",HIGHEVN,ID);
  char* event13= Form("makeEventSample(%i,%i,350,8000)",HIGHEVN,ID);
  char* event14= Form("makeEventSample(%i,%i,350,13000)",HIGHEVN,ID);
  char* event15= Form("makeEventSample(%i,%i,350,14000)",HIGHEVN,ID);
  gROOT->ProcessLine(".L PYTHIALoop2.C");
  gROOT->ProcessLine(event1);
  gROOT->ProcessLine(event2);
  gROOT->ProcessLine(event3);
  gROOT->ProcessLine(event4);
  gROOT->ProcessLine(event5);
  gROOT->ProcessLine(event6);
  gROOT->ProcessLine(event7);
  gROOT->ProcessLine(event8);
  gROOT->ProcessLine(event9);
  gROOT->ProcessLine(event10);
  gROOT->ProcessLine(event11);
  gROOT->ProcessLine(event12);
  gROOT->ProcessLine(event13);
  gROOT->ProcessLine(event14);
  gROOT->ProcessLine(event15);
  gROOT->ProcessLine(".x RunAnalysis.cpp");
}
